{"name": "Проверка перехода в раздел «История заказов»", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <tests.test_personal_account.TestPersonalAccount object at 0x000001C26D80C2C0>, driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bf1b0ae7f8f8e567339ec5d8ffe416ec\")>, login = ['lspencer@yahoo.com', 'vasgw', 'Tina']\n\n    @allure.title('Проверка перехода в раздел «История заказов»')\n    def test_go_to_history_orders_section(self, driver, login):\n        main_page = MainPage(driver)\n        main_page.open(Urls.URL_SB)\n        main_page.click_on_login_in_account_button()\n        login_page = LoginPage(driver)\n        login_page.login_user(login[0], login[1])\n        main_page = MainPage(driver)\n        main_page.click_on_personal_account_button()\n        account_page = AccountPage(driver)\n        account_page.click_on_history_orders_button()\n>       account_page.check_order_history_list_is_displayed()\n\ntests\\test_personal_account.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\account_page.py:23: in check_order_history_list_is_displayed\n    assert self.element_is_visible(self.locators.ORDER_HISTORY_LIST).is_displayed()\npages\\base_page.py:16: in element_is_visible\n    return WebDriverWait(self.driver, timeout=10).until(EC.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"bf1b0ae7f8f8e567339ec5d8ffe416ec\")>, method = <function visibility_of_element_located.<locals>._predicate at 0x000001C26DA7D6C0>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "steps": [{"name": "Клик по кнопке \"Войти в аккаунт\"", "status": "passed", "start": 1716720778045, "stop": 1716720778114}, {"name": "Авторизоваться", "status": "passed", "parameters": [{"name": "email", "value": "'lspencer@yahoo.com'"}, {"name": "password", "value": "'vasgw'"}], "start": 1716720778114, "stop": 1716720778295}, {"name": "Клик по кнопке \"Личный Кабинет\"", "status": "passed", "start": 1716720778295, "stop": 1716720778843}, {"name": "Клик по кнопке \"История заказов\"", "status": "passed", "start": 1716720778843, "stop": 1716720779401}, {"name": "Проверка, что история заказов появилась на экране", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\Marty\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Marty\\PycharmProjects\\Diplom\\Diplom_3\\pages\\account_page.py\", line 23, in check_order_history_list_is_displayed\n    assert self.element_is_visible(self.locators.ORDER_HISTORY_LIST).is_displayed()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Marty\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 16, in element_is_visible\n    return WebDriverWait(self.driver, timeout=10).until(EC.visibility_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Marty\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1716720779401, "stop": 1716720790696}], "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1716720775503, "stop": 1716720790697, "uuid": "ce83a9cc-7583-4a41-95f4-2fc15a5fcb4c", "historyId": "8a82165a3e73da4df9d397e70cd89f55", "testCaseId": "35b668feb60bf4612540a1c88d75c3b7", "fullName": "tests.test_personal_account.TestPersonalAccount#test_go_to_history_orders_section", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_personal_account"}, {"name": "subSuite", "value": "TestPersonalAccount"}, {"name": "host", "value": "DESKTOP-BIEHISL"}, {"name": "thread", "value": "16232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_personal_account"}]}